### ISSUE TITLE
npm start fails at prestart script

### ISSUE THREAD

**Issue by mishakrul** [Jarmahent/Clippy#13]
I am receiving the following error after running `npm start`:

```
C:\Users\Misha\Desktop\Clippy>npm start

> Clippy@0.83.8 prestart C:\Users\Misha\Desktop\Clippy
> yarn build

yarn run v1.13.0
$ concurrently "yarn build-main" "yarn build-renderer"
 Error occured when executing command: yarn build-rendererError: spawn cmd.exe ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
     at onErrorNT (internal/child_process.js:421:16)
     at internalTickCallback (internal/process/next_tick.js:72:19)
     at process._tickCallback (internal/process/next_tick.js:47:5)
     at Function.Module.runMain (internal/modules/cjs/loader.js:779:11)
     at executeUserCode (internal/bootstrap/node.js:342:17)
     at startExecution (internal/bootstrap/node.js:276:5)
     at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)Error occured when executing command: yarn build-rendererError: spawn cmd.exe ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
     at onErrorNT (internal/child_process.js:421:16)
     at internalTickCallback (internal/process/next_tick.js:72:19)
     at process._tickCallback (internal/process/next_tick.js:47:5)
     at Function.Module.runMain (internal/modules/cjs/loader.js:779:11)
     at executeUserCode (internal/bootstrap/node.js:342:17)
     at startExecution (internal/bootstrap/node.js:276:5)
     at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)yarn build-renderer exited with code -4058
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Clippy@0.83.8 prestart: `yarn build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Clippy@0.83.8 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Misha\AppData\Roaming\npm-cache\_logs\2019-01-16T13_37_13_075Z-debug.log
```

I've been trying [various things](https://github.com/Jarmahent/Clippy/issues/9#issuecomment-454779479) for the past 3 days to get this to run properly.  I'm a bit of a node newb so I'm wondering if maybe I'm just missing a step somewhere? 😞

**Comment by Jarmahent** [comment]
run `npm dev` instead of start.

**Comment by mishakrul** [comment]
Finally making some progress.  `npm dev` was failing also with `"Error: spawn yarn ENOENT at notFoundError"`.  Turns out I needed to install yarn, install the dependencies with yarn, `yarn build-dll`, and then `npm run dev`.

![capture](https://user-images.githubusercontent.com/16310249/51313235-15947200-1a1b-11e9-8169-b3d0ac2b0d48.JPG)

A Developer Tools window has opened up upon running `npm run dev` but unfortunately I am still unable to run the server due to the same error mentioned above.

**Comment by Jarmahent** [comment]
Why not insta yarn and run everything with yarn? It's what I do. 

Just:

`yarn dev`
