### ISSUE TITLE
Copy image to clipboard when they're clicked on

### ISSUE THREAD

**Issue by Jarmahent** [Jarmahent/Clippy#6]

**Comment by mishakrul** [comment]
I would like to work on this feature :)

**Comment by Jarmahent** [comment]
@mishakrul awesome just clone the development repo and do `npm i` And if you need anything answered just ask it here

**Comment by mishakrul** [comment]
@Jarmahent I'm receiving some errors after I run `npm i`.  

```
C:\Users\Misha\Desktop\Clippy\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\Misha\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Misha\AppData\Roaming\nvm\v11.4.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Misha\AppData\Local\Programs\Python\Python37\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Misha\\AppData\\Roaming\\nvm\\v11.4.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Misha\Desktop\Clippy\node_modules\integer
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
```

**Comment by Jarmahent** [comment]
Refer to issue #9

**Comment by Jarmahent** [comment]
@mishakrul  Also pay attention to #10 because the app wont start without the `token` filled in the sqlite3 table

**Comment by mmadsoup** [comment]
Hello, I'd love to give this issue a shot, if it's still up for grabs!

**Comment by Jarmahent** [comment]
@snailscode Hey! I havent worked on this app in almost 6 months. I dont even know if it can run at this point. If you want to you can clone it and use it for yourself!
